#!/bin/csh

# USERS MUST CHANGE THESE !!!!!!
set SWIFT_DIR=~/a/2_Pallas/pallas-1/swift/
#set FORTRAN=f77
#set FORTRAN=omf77
set FORTRAN=gfortran
set FFLAGS='-c -O3'

# To Profile the code:
#set FFLAGS='-G -c'


foreach file (*.f)
    echo $file | set file2=`awk -F"." '{print$1}'`
    echo $file2
    $FORTRAN $FFLAGS "$file2".f
    ar vr $SWIFT_DIR/libswift.a  "$file2".o
end

rm *.o
echo Done directory $PWD 
